import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tsvPath = path.join(repoRoot, "data", "hokkien_hanri_dict.tsv");
const hanriCharRe = /[\u3400-\u4dbf\u4e00-\u9fff\u{20000}-\u{2ebef}]/gu;
const hanriCheckRe = /[\u3400-\u4dbf\u4e00-\u9fff\u{20000}-\u{2ebef}]/u;
const hangulRe = /[\u1100-\u11ff\u3130-\u318f\uac00-\ud7af]/u;

const fallbackGloss = new Map(Object.entries({
  一: "one",
  二: "two",
  三: "three",
  四: "four",
  五: "five",
  六: "six",
  七: "seven",
  八: "eight",
  九: "nine",
  十: "ten",
  百: "hundred",
  千: "thousand",
  萬: "ten thousand",
  个: "classifier; individual",
  的: "possessive marker",
  人: "person; people",
  囝: "child",
  仔: "diminutive suffix",
  兒: "child; son",
  母: "mother",
  父: "father",
  兄: "elder brother",
  弟: "younger brother",
  姊: "elder sister",
  妹: "younger sister",
  家: "home; family",
  口: "mouth",
  手: "hand",
  心: "heart; mind",
  肝: "liver",
  目: "eye",
  耳: "ear",
  頭: "head",
  身: "body",
  面: "face; surface",
  水: "water",
  火: "fire",
  風: "wind",
  雨: "rain",
  天: "sky; day",
  地: "earth; place",
  山: "mountain",
  海: "sea",
  日: "day; sun",
  月: "moon; month",
  年: "year",
  時: "time",
  暝: "night",
  早: "early; morning",
  後: "after; behind",
  前: "before; front",
  上: "above; on",
  下: "below; under",
  中: "middle; in",
  內: "inside",
  外: "outside",
  東: "east",
  西: "west",
  南: "south",
  北: "north",
  大: "big; great",
  小: "small",
  老: "old",
  新: "new",
  好: "good",
  歹: "bad",
  紅: "red",
  白: "white",
  黑: "black",
  青: "blue; green",
  色: "color",
  食: "eat",
  飲: "drink",
  行: "walk; go",
  走: "run; leave",
  來: "come",
  去: "go",
  回: "return",
  轉: "turn; return",
  到: "arrive; reach",
  叫: "call",
  講: "speak; say",
  問: "ask",
  聽: "listen; hear",
  看: "look; watch",
  見: "see",
  知: "know",
  想: "think; want",
  愛: "love; want",
  欲: "want; about to",
  有: "have",
  無: "not have; no",
  是: "be; yes",
  會: "can; meeting",
  做: "do; make",
  用: "use",
  拍: "hit; beat",
  放: "put; release",
  開: "open",
  關: "close",
  買: "buy",
  賣: "sell",
  錢: "money",
  箍: "dollar; ring",
  物: "thing",
  事: "matter; affair",
  啥: "what",
  底: "where; which",
  誰: "who",
  問題: "question; problem",
  世界: "world",
  國: "country",
  省: "province",
  市: "city",
  街: "street",
  路: "road",
  店: "shop",
  厝: "house",
  門: "door",
  房: "room; house",
  學: "learn; study",
  校: "school",
  書: "book",
  字: "character; word",
  話: "speech; language",
  語: "language",
  音: "sound",
  歌: "song",
  戲: "play; drama",
  茶: "tea",
  飯: "rice; meal",
  麵: "noodles",
  米: "rice",
  粉: "flour; powder",
  粿: "rice cake",
  菜: "vegetable; dish",
  肉: "meat",
  魚: "fish",
  蝦: "shrimp",
  雞: "chicken",
  豬: "pig",
  牛: "cow",
  馬: "horse",
  鬼: "ghost",
  神: "deity; spirit",
  王: "king",
  君: "lord; ruler",
  官: "official",
  兵: "soldier",
  頂: "top",
  尾: "tail; end",
  邊: "side",
  款: "type; style",
  種: "kind; type",
  點: "point; dot",
  半: "half",
  全: "whole; all",
  總: "total; general",
  真: "true; really",
  正: "correct; proper",
  直: "straight",
  亂: "chaotic; random",
  平: "flat; ordinary",
  常: "usual; constant",
  便: "convenient",
  當: "when; should",
  然: "so; thus",
  後: "after; behind",
  所: "place; that which",
  過: "pass; exceed",
  起: "rise; start",
  結: "tie; knot",
  婚: "marriage",
  情: "feeling; affection",
  感: "feel; sense",
  覺: "feel; perceive",
  影: "shadow; image",
  要: "important; want",
  緊: "tight; urgent",
  著: "hit; correct; wear",
  插: "insert",
  炒: "fry",
  吵: "noisy; argue",
  煮: "cook; boil",
  洗: "wash",
  穿: "wear; pierce",
  踏: "step on; tread",
  蹛: "stay; live at",
  坐: "sit",
  睏: "sleep",
  病: "illness",
  死: "die",
  生: "life; give birth",
  活: "live; alive",
  煞: "finish; suddenly",
  別: "other; different",
  朋: "friend",
  友: "friend",
  親: "relative; close",
  老師: "teacher",
  學生: "student",
  公司: "company",
  機: "machine; opportunity",
  場: "field; place",
  工: "work",
  車: "vehicle",
  船: "boat",
  電: "electricity",
  腦: "brain",
}));

const extraFallbackGloss = {
  "㩼": "work; labor",
  "䀐": "look; glance",
  "䭕": "food; snack",
  "久": "long time",
  "乖": "obedient; well-behaved",
  "了": "completed; finished",
  "亡": "dead; deceased",
  "交": "exchange; hand over",
  "亭": "pavilion",
  "仇": "enemy; hatred",
  "今": "now; present",
  "介": "introduce; between",
  "他": "he; other",
  "付": "pay; hand over",
  "仙": "immortal; fairy",
  "仝": "same; together",
  "代": "generation; replace",
  "以": "use; by means of",
  "仰": "admire; look up",
  "件": "item; piece",
  "任": "responsibility; duty",
  "份": "share; portion",
  "伏": "submit; hide",
  "伴": "companion; accompany",
  "但": "but; only",
  "位": "place; position",
  "低": "low",
  "佑": "protect; bless",
  "何": "what; how",
  "佩": "wear; admire",
  "佮": "and; with",
  "依": "rely on; according to",
  "俗": "custom; common",
  "保": "protect; keep",
  "修": "repair; cultivate",
  "俳": "clowning; comedy",
  "個": "individual; classifier",
  "倒": "fall; reverse",
  "倚": "lean on",
  "借": "borrow; lend",
  "假": "false; fake",
  "偏": "partial; one-sided",
  "健": "healthy; strong",
  "偷": "steal; secretly",
  "備": "prepare",
  "催": "urge; hurry",
  "傳": "transmit; legend",
  "像": "image; resemble",
  "儉": "frugal; economical",
  "克": "overcome; restrain",
  "兔": "rabbit",
  "兜": "pocket; around",
  "兼": "also; concurrently",
  "冊": "book; volume",
  "再": "again",
  "冤": "wronged; injustice",
  "凊": "cold; cool",
  "凍": "freeze; cold",
  "凡": "ordinary; all",
  "出": "go out; produce",
  "切": "cut; urgent",
  "初": "beginning; first",
  "判": "judge; decide",
  "利": "benefit; profit",
  "制": "control; system",
  "刻": "carve; moment",
  "削": "cut; pare",
  "創": "create; wound",
  "劃": "mark; plan",
  "劇": "drama; severe",
  "劉": "Liu; surname",
  "劍": "sword",
  "力": "strength; power",
  "加": "add; increase",
  "劫": "robbery; calamity",
  "動": "move; action",
  "勞": "labor; toil",
  "勢": "force; situation",
  "勤": "diligent",
  "勸": "advise; persuade",
  "化": "change; transform",
  "匙": "spoon; key",
  "區": "area; district",
  "升": "rise; ascend",
  "博": "broad; doctorate",
  "印": "mark; print",
  "厚": "thick; generous",
  "原": "original; source",
  "又": "again; also",
  "叉": "fork; cross",
  "反": "opposite; turn against",
  "受": "receive; suffer",
  "古": "ancient; old",
  "不": "not; no",
  "台": "platform; Taiwan",
  "各": "each",
  "同": "same; together",
  "名": "name; reputation",
  "吐": "spit; vomit",
  "向": "toward; direction",
  "吞": "swallow",
  "含": "contain; hold in the mouth",
  "吹": "blow",
  "吼": "roar; shout",
  "呆": "dull; foolish",
  "告": "tell; announce",
  "味": "taste; flavor",
  "和": "and; with; harmony",
  "品": "goods; quality",
  "只": "only; just",
  "可": "can; may",
  "哪": "which; where",
  "哭": "cry",
  "唱": "sing",
  "啼": "cry; crow",
  "喉": "throat",
  "喘": "pant; gasp",
  "喙": "mouth; beak",
  "喜": "joy; like",
  "嚨": "throat",
  "嚴": "strict; solemn",
  "囂": "noisy; arrogant",
  "囥": "hide; store away",
  "困": "trapped; sleepy",
  "園": "garden; park",
  "圓": "round; complete",
  "在": "exist; at",
  "坎": "pit; uneven",
  "坑": "pit; hole",
  "坷": "rough; uneven",
  "城": "city; wall",
  "培": "cultivate; foster",
  "堂": "hall",
  "堪": "can bear; worthy",
  "塗": "earth; smear",
  "墘": "edge; side",
  "士": "scholar; specialist",
  "壽": "longevity",
  "多": "many; much",
  "太": "too; very",
  "夭": "die young; tender",
  "夯": "carry; lift",
  "奅": "empty; hollow",
  "奈": "how; endure",
  "奮": "exert; vigorous",
  "女": "woman; female",
  "妄": "reckless; absurd",
  "妖": "demon; strange",
  "妗": "aunt",
  "妝": "makeup; adorn",
  "姓": "surname",
  "委": "entrust; bend",
  "娜": "graceful",
  "婀": "graceful",
  "婿": "son-in-law; husband",
  "媠": "beautiful",
  "嫌": "dislike; suspect",
  "孔": "hole",
  "存": "exist; keep",
  "孝": "filial piety",
  "孫": "grandchild",
  "孽": "evil; sin",
  "宇": "universe; house",
  "守": "guard; keep",
  "完": "complete; finish",
  "宙": "universe; time",
  "客": "guest; customer",
  "室": "room; chamber",
  "害": "harm",
  "容": "appearance; contain",
  "宿": "lodging; destiny",
  "寂": "quiet; lonely",
  "寄": "send; lodge",
  "密": "secret; dense",
  "寞": "lonely; silent",
  "寧": "peaceful; rather",
  "審": "judge; examine",
  "寫": "write",
  "寶": "treasure; precious",
  "將": "will; general",
  "尊": "honorable; respect",
  "就": "then; approach",
  "尻": "buttocks",
  "屁": "fart; nonsense",
  "屈": "bend; wrong",
  "展": "develop; unfold",
  "屜": "drawer",
  "屬": "belong to",
  "岸": "shore; bank",
  "崁": "cliff; ridge",
  "川": "river",
  "巧": "skillful; clever",
  "己": "self",
  "已": "already",
  "布": "cloth; spread",
  "希": "hope; rare",
  "帝": "emperor",
  "帶": "bring; belt",
  "幸": "fortunate; happiness",
  "幻": "illusion; transform",
  "幼": "young",
  "幾": "how many; several",
  "庇": "protect; shelter",
  "床": "bed",
  "度": "degree; measure",
  "座": "seat; classifier",
  "康": "healthy; peaceful",
  "延": "extend; delay",
  "建": "build; establish",
  "張": "open; surname",
  "彈": "play; spring",
  "彩": "color; prize",
  "彷": "seem; wander",
  "待": "wait; treat",
  "得": "obtain; can",
  "徛": "stand",
  "從": "from; follow",
  "徨": "wander; hesitate",
  "微": "slight; subtle",
  "必": "must",
  "忍": "endure",
  "忘": "forget",
  "快": "fast; happy",
  "忽": "sudden; neglect",
  "怎": "how",
  "思": "think; miss",
  "恨": "hate; regret",
  "恩": "kindness; grace",
  "恬": "quiet; calm",
  "息": "rest; breath",
  "悄": "quietly",
  "悲": "sad",
  "悽": "sad; miserable",
  "悾": "foolish; empty-headed",
  "惰": "lazy",
  "惱": "annoyed; trouble",
  "愈": "more; recover",
  "慈": "kind; compassionate",
  "態": "state; attitude",
  "慐": "foolish; stunned",
  "慘": "miserable; tragic",
  "憐": "pity; love",
  "憑": "rely on; evidence",
  "憾": "regret",
  "應": "should; respond",
  "懷": "harbor; miss",
  "戀": "love; long for",
  "成": "become; accomplish",
  "打": "hit; strike",
  "扛": "carry; lift",
  "扮": "dress up; disguise",
  "批": "batch; criticize; letter",
  "投": "throw; invest",
  "折": "break; fold",
  "抱": "hold; embrace",
  "抽": "draw out; pull",
  "拄": "just; prop up",
  "拆": "take apart; dismantle",
  "拈": "pick up with fingers",
  "拔": "pull out; remove",
  "拖": "drag; delay",
  "招": "invite; recruit",
  "拜": "worship; visit",
  "拭": "wipe",
  "指": "finger; point",
  "按": "press; according to",
  "挑": "pick; carry",
  "挨": "endure; next to",
  "挭": "block; choke",
  "振": "shake; revive",
  "挵": "hit; knock",
  "捌": "know; recognize",
  "捍": "defend; guard",
  "捧": "hold up; praise",
  "掘": "dig",
  "掠": "catch; seize",
  "採": "pick; gather",
  "接": "receive; connect",
  "揀": "choose",
  "提": "carry; mention",
  "換": "change; exchange",
  "揞": "cover; hide",
  "揣": "look for; guess",
  "搬": "move; carry",
  "摻": "mix in",
  "撇": "cast aside; skim",
  "撥": "push aside; allocate",
  "撨": "adjust; arrange",
  "擋": "block; stop",
  "擔": "carry; burden",
  "擘": "split; break open",
  "擲": "throw",
  "擺": "put; arrange",
  "攑": "raise; lift",
  "攝": "take in; photograph",
  "攤": "spread out; stall",
  "支": "branch; support",
  "收": "receive; collect",
  "政": "government; politics",
  "故": "old; reason",
  "教": "teach; religion",
  "敢": "dare",
  "散": "scatter; loose",
  "敲": "knock",
  "斟": "pour; consider",
  "斡": "turn; manage",
  "斷": "break; decide",
  "方": "direction; method",
  "於": "at; in",
  "施": "carry out; bestow",
  "旅": "travel",
  "旋": "turn; spin",
  "旗": "flag",
  "昏": "dusk; dim",
  "星": "star",
  "春": "spring",
  "昨": "yesterday",
  "晟": "bright; flourishing",
  "普": "general; common",
  "暖": "warm",
  "暢": "smooth; carefree",
  "曉": "dawn; understand",
  "曝": "expose to sun",
  "更": "more; again",
  "替": "replace",
  "望": "hope; look",
  "朝": "morning; dynasty",
  "期": "period; expect",
  "木": "wood; tree",
  "李": "plum; surname",
  "束": "bind; bundle",
  "林": "forest; surname",
  "枷": "cangue; shackle",
  "柔": "soft; gentle",
  "栽": "plant; cultivate",
  "桃": "peach",
  "框": "frame",
  "桑": "mulberry",
  "梅": "plum blossom",
  "棟": "ridgepole; building",
  "森": "forest; dense",
  "椒": "pepper",
  "楊": "willow; surname",
  "楚": "suffering; clear",
  "業": "work; karma",
  "槌": "hammer; beat",
  "模": "model; pattern",
  "樣": "appearance; manner",
  "樹": "tree",
  "橋": "bridge",
  "櫥": "cabinet",
  "欠": "owe; lack",
  "欹": "tilted; leaning",
  "歡": "happy; welcome",
  "此": "this",
  "歲": "year; age",
  "歸": "return; belong to",
  "殘": "remaining; cruel",
  "段": "section; paragraph",
  "每": "each; every",
  "毒": "poison",
  "氣": "air; energy",
  "求": "seek; request",
  "沃": "water; fertile",
  "沉": "sink; deep",
  "沖": "rush; rinse",
  "沙": "sand",
  "河": "river",
  "治": "govern; treat",
  "法": "law; method",
  "泡": "soak; bubble",
  "波": "wave",
  "浮": "float",
  "消": "disappear; remove",
  "液": "liquid",
  "淋": "drench; pour",
  "淚": "tears",
  "深": "deep",
  "淺": "shallow",
  "清": "clear; pure",
  "減": "reduce",
  "港": "harbor; Hong Kong",
  "湖": "lake",
  "湧": "surge; well up",
  "湯": "soup; hot water",
  "準": "accurate; standard",
  "溫": "warm; gentle",
  "滄": "dark blue; vast",
  "滋": "nourish; flavor",
  "滴": "drop; drip",
  "滷": "brine; stew",
  "滿": "full",
  "漂": "float; beautiful",
  "演": "perform; develop",
  "漢": "Han; Chinese",
  "漸": "gradually",
  "潘": "Pan; surname",
  "澀": "rough; astringent",
  "澹": "calm; watery",
  "激": "excite; intense",
  "灣": "bay",
  "灶": "stove",
  "炎": "flame; inflammation",
  "烌": "warm; roast",
  "烙": "brand; bake",
  "煙": "smoke",
  "煠": "boil; blanch",
  "煩": "annoyed; troublesome",
  "爛": "rotten; overcooked",
  "爬": "climb; crawl",
  "爸": "father",
  "爿": "side; half",
  "片": "piece; slice",
  "牚": "prop up; support",
  "牢": "firm; prison",
  "牲": "sacrifice; livestock",
  "牽": "lead; pull",
  "犁": "plow",
  "犧": "sacrifice",
  "狡": "crafty; cunning",
  "狼": "wolf",
  "狽": "distressed; embarrassed",
  "猛": "fierce",
  "猶": "still; as if",
  "獄": "prison; hell",
  "獻": "offer; present",
  "玲": "tinkling; delicate",
  "現": "present; appear",
  "琴": "string instrument",
  "琵": "pipa",
  "琶": "pipa",
  "瑯": "gem sound; bright",
  "環": "ring; surrounding",
  "田": "field",
  "由": "from; reason",
  "男": "male; man",
  "留": "stay; keep",
  "異": "different; strange",
  "疑": "doubt; suspect",
  "疼": "pain; love",
  "痀": "hunchback",
  "痕": "mark; scar",
  "痛": "pain",
  "痧": "heat rash; illness",
  "痴": "foolish; infatuated",
  "發": "send out; develop",
  "皇": "emperor; royal",
  "皮": "skin; leather",
  "盡": "exhaust; all",
  "眠": "sleep",
  "眼": "eye",
  "破": "break; broken",
  "硬": "hard",
  "碌": "busy; stone roller",
  "碩": "large; master's degree",
  "磅": "pound; weigh",
  "磨": "grind; torment",
  "礙": "obstruct",
  "祈": "pray",
  "祐": "bless; protect",
  "祝": "wish; bless",
  "票": "ticket",
  "福": "blessing; good fortune",
  "秋": "autumn",
  "秘": "secret",
  "稀": "rare; thin",
  "稚": "young; childish",
  "穩": "stable",
  "空": "empty; air",
  "窗": "window",
  "站": "station; stand",
  "笑": "laugh; smile",
  "筆": "pen; brush",
  "筊": "divination blocks",
  "答": "answer",
  "管": "pipe; manage",
  "箬": "bamboo leaf",
  "籤": "lot; divination slip",
  "粒": "grain; particle",
  "粗": "coarse; rough",
  "糖": "sugar",
  "糜": "porridge",
  "約": "agreement; about",
  "紋": "pattern; line",
  "紲": "continue; connect",
  "紹": "continue; introduce",
  "終": "end; finally",
  "絕": "cut off; despair",
  "絲": "silk; thread",
  "網": "net; web",
  "緣": "fate; connection",
  "緻": "fine; delicate",
  "縒": "wrong; uneven",
  "縛": "bind; tie",
  "繁": "complex; flourishing",
  "繼": "continue; inherit",
  "續": "continue",
  "纏": "entangle",
  "罵": "scold",
  "羅": "net; gather",
  "翁": "old man; father-in-law",
  "翕": "close; gather",
  "考": "test; consider",
  "而": "and; but",
  "耐": "endure",
  "耽": "delay; indulge",
  "聊": "chat; rely on",
  "職": "job; duty",
  "背": "back; betray",
  "胛": "shoulder blade",
  "胸": "chest",
  "能": "ability; can",
  "脊": "spine",
  "脣": "lip",
  "脾": "spleen; temper",
  "腰": "waist",
  "腿": "leg",
  "膚": "skin",
  "臆": "chest; guess",
  "自": "self; from",
  "臭": "smelly",
  "興": "interest; prosper",
  "舒": "comfortable; stretch",
  "舞": "dance",
  "航": "sail; aviation",
  "良": "good; kind",
  "芋": "taro",
  "芒": "awn; miscanthus",
  "芡": "thickening starch",
  "花": "flower",
  "芳": "fragrant",
  "若": "if; like",
  "苦": "bitter; suffering",
  "茉": "jasmine",
  "草": "grass",
  "莉": "jasmine",
  "菅": "cogon grass",
  "菝": "smilax",
  "菩": "bodhisattva",
  "華": "splendid; Chinese",
  "蒜": "garlic",
  "蓋": "cover; lid",
  "蔫": "withered",
  "蕊": "flower bud; stamen",
  "薇": "fern; rose",
  "薑": "ginger",
  "薔": "rose; briar",
  "薟": "spicy; pungent",
  "薩": "bodhisattva",
  "薰": "fragrant; smoke",
  "藏": "hide; store",
  "藥": "medicine",
  "虎": "tiger",
  "處": "place; deal with",
  "虛": "empty; weak",
  "號": "number; call",
  "虧": "loss; owe",
  "蚵": "oyster",
  "蚶": "clam",
  "蚼": "ant",
  "蟲": "insect; worm",
  "蟳": "crab",
  "蟻": "ant",
  "血": "blood",
  "衝": "rush; collide",
  "衡": "balance; weigh",
  "表": "surface; express",
  "衰": "decline; unlucky",
  "衷": "inner feeling",
  "袋": "bag",
  "裝": "install; dress",
  "裡": "inside",
  "褲": "pants",
  "規": "rule; plan",
  "覕": "hide; conceal",
  "角": "corner; horn",
  "解": "explain; untie",
  "觸": "touch; offend",
  "計": "plan; count",
  "訕": "mock; tease",
  "設": "set up; design",
  "試": "try; test",
  "詩": "poem",
  "該": "should; owe",
  "詼": "joke; humorous",
  "誌": "record; journal",
  "認": "recognize; admit",
  "誠": "sincere; honest",
  "誤": "mistake; delay",
  "說": "say; explain",
  "談": "talk; discuss",
  "請": "please; invite",
  "諒": "forgive; understand",
  "論": "discuss; theory",
  "諺": "proverb",
  "謙": "modest",
  "謝": "thank; apologize",
  "譀": "boast; exaggerate",
  "證": "prove; certificate",
  "譜": "score; record",
  "議": "discuss; opinion",
  "護": "protect",
  "讀": "read; study",
  "讚": "praise",
  "負": "carry; betray",
  "貧": "poor",
  "責": "responsibility; blame",
  "貴": "expensive; noble",
  "賭": "gamble",
  "賰": "left over; surplus",
  "贏": "win",
  "趁": "take advantage; while",
  "趣": "interest; fun",
  "足": "enough; foot",
  "跡": "trace; mark",
  "跤": "foot",
  "跳": "jump",
  "踅": "turn around; wander",
  "踮": "stand on tiptoe; stay",
  "踱": "pace; walk",
  "蹤": "trace; track",
  "軀": "body",
  "輕": "light; easy",
  "輝": "radiance",
  "輸": "lose; transport",
  "辛": "hard; bitter",
  "辭": "resign; words",
  "迎": "welcome",
  "追": "chase; pursue",
  "送": "send; give",
  "透": "through; thoroughly",
  "逐": "chase; each",
  "途": "road; journey",
  "通": "pass through; understand",
  "逝": "pass away; go",
  "造": "make; create",
  "連": "connect; even",
  "逼": "force; press",
  "道": "road; way",
  "達": "reach; achieve",
  "遠": "far",
  "遣": "send; dispatch",
  "遺": "leave behind; regret",
  "還": "still; return",
  "郁": "luxuriant; anxious",
  "部": "department; section",
  "鄉": "hometown; countryside",
  "酌": "pour; consider",
  "配": "match; distribute",
  "醋": "vinegar; jealousy",
  "醒": "wake; sober",
  "醫": "medicine; doctor",
  "野": "wild; field",
  "鉛": "lead; pencil",
  "銃": "gun",
  "銷": "sell; melt",
  "錐": "awl; pointed",
  "錯": "wrong; mistake",
  "鎖": "lock",
  "鏈": "chain",
  "鏡": "mirror",
  "鐵": "iron",
  "鑽": "drill; bore",
  "鑿": "chisel; dig",
  "長": "long; grow",
  "閃": "flash; dodge",
  "閉": "close; shut",
  "間": "between; room",
  "闊": "wide",
  "阻": "block; hinder",
  "阿": "prefix for names",
  "降": "descend; subdue",
  "限": "limit",
  "隨": "follow; according to",
  "隱": "hide; hidden",
  "隻": "single; classifier",
  "雄": "male; heroic",
  "雙": "pair; double",
  "離": "leave; apart",
  "難": "difficult; disaster",
  "雪": "snow",
  "雲": "cloud",
  "霜": "frost",
  "靈": "spirit; effective",
  "靜": "quiet; still",
  "靠": "lean on; rely on",
  "鞭": "whip",
  "響": "sound; echo",
  "項": "item; neck",
  "頷": "chin; nod",
  "頸": "neck",
  "顆": "grain; classifier",
  "題": "topic; question",
  "願": "wish; willing",
  "顛": "top; crazy",
  "飄": "float; flutter",
  "飼": "feed; raise",
  "飽": "full; satisfied",
  "養": "raise; nourish",
  "首": "head; first",
  "香": "fragrant",
  "騎": "ride",
  "騙": "deceive",
  "驗": "verify; experience",
  "骨": "bone",
  "體": "body; form",
  "高": "tall; high",
  "鬆": "loose; relaxed",
  "魂": "soul",
  "鮮": "fresh",
  "鰡": "mullet fish",
  "鴉": "crow",
  "黏": "sticky",
  "鼎": "pot; cauldron",
  "鼓": "drum",
  "鼠": "rat; mouse",
  "鼻": "nose",
  "𤆬": "lead; bring",
};

for (const [key, gloss] of Object.entries(extraFallbackGloss)) {
  if (!fallbackGloss.has(key)) {
    fallbackGloss.set(key, gloss);
  }
}

function hanriChars(value) {
  return [...String(value || "").matchAll(hanriCharRe)].map((match) => match[0]);
}

function hanriOnlyKey(value) {
  return hanriChars(value).join("");
}

function isPlainHanri(value) {
  const text = String(value || "");
  return hanriCheckRe.test(text) && !hangulRe.test(text);
}

function normalizeEnglish(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function mergeGlosses(glosses) {
  const seen = new Set();
  const merged = [];
  for (const gloss of glosses.map(normalizeEnglish).filter(Boolean)) {
    for (const part of gloss.split(";")) {
      const item = normalizeEnglish(part);
      const key = item.toLowerCase();
      if (!item || seen.has(key)) continue;
      seen.add(key);
      merged.push(item);
    }
  }
  return merged.slice(0, 5).join("; ");
}

const raw = fs.readFileSync(tsvPath, "utf8").replace(/^\uFEFF/, "");
const rows = raw.split(/\r?\n/);
const header = rows.shift();
const kept = [];
const seenRows = new Set();
let duplicateRowsRemoved = 0;

for (const row of rows) {
  if (!row.trim()) continue;
  if (seenRows.has(row)) {
    duplicateRowsRemoved += 1;
    continue;
  }
  seenRows.add(row);
  kept.push(row);
}

const parsed = kept.map((line) => {
  const columns = line.split("\t");
  while (columns.length < 5) columns.push("");
  return columns;
});

const exactGlossByHanri = new Map();
const exactGlossByHanriOnly = new Map();
const singleCharGloss = new Map(fallbackGloss);

for (const columns of parsed) {
  const [reading, hanri, , , english] = columns;
  if (!reading || reading.startsWith("#")) continue;
  if (!isPlainHanri(hanri)) continue;
  const gloss = normalizeEnglish(english);
  if (!gloss) continue;

  if (!exactGlossByHanri.has(hanri)) {
    exactGlossByHanri.set(hanri, gloss);
  }

  const key = hanriOnlyKey(hanri);
  if (key) {
    if (!exactGlossByHanriOnly.has(key)) {
      exactGlossByHanriOnly.set(key, gloss);
    }
    if ([...key].length === 1 && !singleCharGloss.has(key)) {
      singleCharGloss.set(key, gloss);
    }
  }
}

let copiedSameHanri = 0;
let copiedHanriOnly = 0;
let filledFromComponents = 0;

for (const columns of parsed) {
  const [reading, hanri] = columns;
  if (!reading || reading.startsWith("#") || normalizeEnglish(columns[4])) continue;
  if (!isPlainHanri(hanri)) continue;

  let gloss = exactGlossByHanri.get(hanri);
  if (gloss) {
    copiedSameHanri += 1;
  } else {
    const hanriOnly = hanriOnlyKey(hanri);
    gloss = exactGlossByHanriOnly.get(hanriOnly);
    if (gloss) {
      copiedHanriOnly += 1;
    } else {
      const chars = [...hanriOnly];
      const charGlosses = chars.map((char) => singleCharGloss.get(char)).filter(Boolean);
      if (charGlosses.length) {
        gloss = mergeGlosses(charGlosses);
        filledFromComponents += 1;
      }
    }
  }

  if (gloss) {
    columns[4] = gloss;
  }
}

const output = [header, ...parsed.map((columns) => columns.slice(0, 5).join("\t"))].join("\n") + "\n";
fs.writeFileSync(tsvPath, output, "utf8");

const remainingBlankHanri = parsed.filter((columns) => {
  const [reading, hanri, , , english] = columns;
  return reading && !reading.startsWith("#") && isPlainHanri(hanri) && !normalizeEnglish(english);
}).length;

console.log(JSON.stringify({
  duplicateRowsRemoved,
  copiedSameHanri,
  copiedHanriOnly,
  filledFromComponents,
  remainingBlankHanri,
}, null, 2));
